spring:
  application:
    name: eurekaserver
  security:
    basic:
      enabled: true
    user:
      name: user #swap for environment variables
      password: user #swap for environment variables

server:
  port: 8761

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
