spring:
  application:
    name: course-ms
  servlet:
    multipart:
      max-file-size: 600MB
      max-request-size: 600MB
  rabbitmq:
    host: localhost
    port: 5672
    username: guest #change in the future due to environment variables
    password: guest #change in the future due to environment variables
    virtual-host: /
  datasource:
    username: postgres #change in production
    url: jdbc:postgresql://localhost:5432/course
    password: 1234 #change in production
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update

mq:
  queue:
    courses-for-student: "courses-for-student"

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://user:user@localhost:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

material-module: "C:/faculty/material-module"

#actuator config
management:
  endpoints:
    web:
      exposure:
        include: '*'

#logging:
#  file:
#    name: ./logs/log-file.log