spring:
  application:
    name: student-ms
  servlet:
    multipart:
      max-file-size: 600MB
      max-request-size: 600MB
  datasource:
    username: postgres #change in production
    url: jdbc:postgresql://localhost:5432/student
    password: 1234 #change in production
  jpa:
    show-sql: 'true'
    hibernate:
      ddl-auto: update

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
    virtual-host: /

mq:
  queue:
    courses-for-student: "courses-for-student"
    user-for-authentication: "user-for-authentication"

images-students-path: "C:/faculty/images-students"
files-students-path: "C:/faculty/files-students"

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://user:user@localhost:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#actuator config
management:
  endpoints:
    web:
      exposure:
        include: '*'

#logging:
#  file:
#    name: ./logs/log-file.log

