spring:
  application:
    name: msstudent
  servlet:
    multipart:
      max-file-size: 600MB
      max-request-size: 600MB

images-students-path: "C:/faculty/images-students"
files-students-path: "C:/faculty/files-students"

server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    instance:
      instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

#actuator config
management:
  endpoints:
    web:
      exposure:
        include: '*'

logging:
  file:
    name: ./logs/log-file.log

